# Generated by Django 5.0.6 on 2024-07-08 21:35

from django.db import migrations


def create_user_groups(apps, schema_editor):
    """
    Создание основных групп пользователей.
    """

    Group = apps.get_model('auth', 'Group')

    Group.objects.bulk_create([
        Group(name='Customers'),
        Group(name='Employees'),
        Group(name='SuperEmployees'),
    ])


def delete_user_groups(apps, schema_editor):
    """
    Удаление основных групп пользователей.
    """

    Group = apps.get_model('auth', 'Group')

    Group.objects.filter(
        name__in=[
            'Customers',
            'Employees',
            'SuperEmployees',
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_user_groups, delete_user_groups),
    ]
